#+title: readme

Statically typed wrapper for nim ast at compile (~NimNode~) and rutime
(~PNode~). Another take on solving problem of ~node[0][0][1][0]~. Mostly
concerned with processing of types and procedure declarations. Provides
helper API for working with nimble packages.

* Installation

#+begin_src bash
nimble install hnimast
#+end_src

*note*: hnimast relies on the compiler API. In order to avoid mismatches
between nim compiler that you are compiling code with, and actual compiler
API it is necessary to add ~--path:"$nim"~ to your ~nim.cfg~ file. This
also prevents downloading of the whole compiler package, which is by far
the largest dependency.

* Links

- [[https://github.com/haxscramper/hnimast][github]]
- documentation
  - [[https://haxscramper.github.io/hnimast/compiler_aux.html][compiler_aux]] :: Helper procs for interfacing with nim compiler. Common
    module graph setup logic, stdlib search etc.
  - [[https://haxscramper.github.io/hnimast/cst_lexer.html][cst_lexer]], [[https://haxscramper.github.io/hnimast/cst_parser.html][cst_parser]], [[https://haxscramper.github.io/hnimast/cst_types.html][cst_types]] :: Fork of the nim code parser to be
    used for pretty-printing. Stores all positional and comment information.
  - [[https://haxscramper.github.io/hnimast/enum_decl.html][enum_decl]] :: Handle enum declaration - parse and generate
  - [[https://haxscramper.github.io/hnimast/hast_common.html][hast_common]] :: Basic AST construction logic. Provides shared generic
    interface for operating on both ~std/macros.NimNode~ and
    ~compiler/ast.PNode~. Implements huge number of convenience functions
    for constructing different node kinds.
  - [[https://haxscramper.github.io/hnimast/hast_quote.html][hast_quote]] :: Reimplementation of the ~quote do:~ that doesn't gensym
    identifiers, but allows for more complex node interoplation. Provides
    ~nquote do:~ (for ~NimNode~) and ~pquote do:~ (for ~PNode~). Latter one
    can be used for codegen.
  - [[https://haxscramper.github.io/hnimast/idents_types.html][idents_types]] :: Handle type declarations, identifiers
  - [[https://haxscramper.github.io/hnimast/nimble_aux.html][nimble_aux]] :: Helper code for working with nimble. Parse manifest files
    without having to execute external scripts.
  - [[https://haxscramper.github.io/hnimast/nim_decl.html][nim_decl]] :: Wrap different toplevel entry declarations in a single
    variant object.
  - [[https://haxscramper.github.io/hnimast/object_decl.html][object_decl]] :: Type declarations for object parsing
  - [[https://haxscramper.github.io/hnimast/obj_field_macros.html][obj_field_macros]] :: Object parsing implementation
  - [[https://haxscramper.github.io/hnimast/pnode_parse.html][pnode_parse]] :: Wrapper around ~compiler~ 's parser
  - [[https://haxscramper.github.io/hnimast/pragmas.html][pragmas]] :: Pragma processing
  - [[https://haxscramper.github.io/hnimast/proc_decl.html][proc_decl]] :: Procedure declaration processing


* Description

Provides logical structure for objects/fields - you can set/get type,
check if field is a switch for case statement or not. Visit
~eachField~ in the object, map object to some code structure.

#+begin_src nim :exports both
  import hnimast, hnimast/obj_field_macros
  import hpprint

  let node = """
  type Type = object
    hello: float
  """.parsePNodeStr()

  var obj = parseObject(node, parsePPragma)

  echo "# ~~~~ make object exported ~~~~ #"

  obj.exported = true
  echo obj.toNNode()


  echo "# ~~~~ internal structure of object ~~~~ #"
  pprint obj
#+end_src

#+RESULTS:
#+begin_example
# ~~~~ make object exported ~~~~ #
Type* = object
  hello: float

# ~~~~ internal structure of object ~~~~ #
Object[ast.PNode, Pragma[ast.PNode]]
  exported:   true
  annotation:
    Option[Pragma[ast.PNode]]
      val: Pragma[ast.PNode](kind: oakCaseOfBranch, elements: [])
      has: false
  name:
    NType[ast.PNode]
      kind:      ntkIdent
      head:      "Type"
      genParams: []
  flds:
    - ObjectField[ast.PNode, Pragma[ast.PNode]]
        annotation:
          Option[Pragma[ast.PNode]]
            val:
              Pragma[ast.PNode]
                kind:     oakCaseOfBranch
                elements: []
            has: false
        value:      Option[ast.PNode](val: <nil tree>)
        exported:   false
        isTuple:    false
        name:       "hello"
        fldType:
          NType[ast.PNode]
            kind:      ntkIdent
            head:      "float"
            genParams: []
        isKind:     false
#+end_example

- working with enums
  - ~parseEnumImpl~ - parse as enum implementation. Tested on alias,
    symbol, value, enum-as-generic-parameter, ~typedesc[Enum]~ etc.
  - ~getEnumPref~ - for [[https://nim-lang.org/docs/nep1.html#introduction-naming-conventions][NEP-conforming]] enums (~prefixEnumValueName~)
    get ~prefix~
  - ~getEnumNames~ - get list of all enum names
  - ~enumNames~ - macro. Generate ~seq[string]~ of names for all
    enums.
- working with object declarations
  - ~ObjectBranch~, ~Object~ and ~ObjectField~ types - wrappers on top
    of nim object declarations. Supports arbitrarily named case
    fields, annotations for objects etc. Currently does not cover all
    possible cases.
  - ~eachField~ - visit each field in object
  - ~eachField~ - recursively generate ~case~ expression for each
    possible and use insert result of callback for each field. For use
    case example see [[file:tests/tHnimAst.nim]]
  - can be conveted to and from ~NimNode~
  - ~eachCase~ - generate case statement for object's kind fields
  - ~eachParallelCase~ - generate case statement for two object's kind
    fields.
  - ~eachPath~
- working with object values
  - ~ObjTree~ - 'stringly typed' representation of object value.
    mainly used in ~hpprint~, but due to dependency reasons type
    definitions is still here.
