name:
  test
on:
  push
jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, 'WIP')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-6'
      - run: "nimble -y develop"
      - run: |
          echo '--path="$nim"' > nim.cfg
          cat nim.cfg

      - run: "nimble test"
      - run: "nimble docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: htmldocs
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
